DROP TABLE IF EXISTS work_types;

CREATE TABLE IF NOT EXISTS work_types(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(10) NOT NULL CHECK (
        type IN('remote', 'office', 'hybrid')
    )
);