-- DROP TABLE roles;

CREATE TABLE IF NOT EXISTS roles(
    id SERIAL PRIMARY KEY,
    role VARCHAR(50) NOT NULL CHECK (
        role IN('STUDENT', 'ADMIN', 'SUPERADMIN', 'COMPANY', 'UNIVERSITY', 'RECRUITER')
    ) UNIQUE
);


